import {
  Entity,
  Column,
  ManyToMany,
  JoinTable,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { UserOrmEntity } from './user.orm-entity';
import { PermissionOrmEntity } from './permission.orm-entity';
import { BaseOrmEntity } from '@base/infrastructure/entities/base.orm';

@Entity('groups') // Table name for groups
export class GroupOrmEntity extends BaseOrmEntity {
  @PrimaryGeneratedColumn('uuid') // UUID generated by typeorm
  id!: string;
  @Column({ unique: true })
  name!: string; // Name of the group (must be unique)

  @ManyToMany(() => UserOrmEntity, (user) => user.groups)
  users!: UserOrmEntity[]; // Users associated with this group

  @ManyToMany(() => PermissionOrmEntity, (permission) => permission.groups, {
    eager: true,
  })
  @JoinTable({ name: 'group_permissions' }) // Join table for group-permission relationships
  permissions!: PermissionOrmEntity[]; // Permissions associated with this group
}
